name: deploy

on:
  push:
    branches:
      - sources

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get themes
        run: |
          git submodule update --init
          cd themes && git submodule init Flex && cd -
          cd themes && git submodule update && cd -

      - name: Deploy
        uses: nelsonjchen/gh-pages-pelican-action@0.1.10
        #uses:  iranzo/gh-pages-pelican-action@1.0.3
        #run: make publish github
        env:
          GH_PAGES_BRANCH: master
          GH_PAGES_CNAME: fofix.org
          PELICAN_CONFIG_FILE: publishconf.py
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PIWIK_URL: ${{secrets.PIWIK_URL}}
          PIWIK_SITE_ID: ${{secrets.PIWIK_SITE_ID}}
